### ISSUE TITLE
[Undercover] Some elements of HUD are scaled improperly

### ISSUE THREAD

**Issue by HarGabt** [xan1242/NFS_CustomFont#1]
The pack I downloaded for UC has some issues with racing HUD. Maybe, some settings for its .txt file are missing, I dunno.

<details>
  <summary>Screenshots</summary>
  
![Need for Sleep™ Under the Cover_2022 11 11-21 28](https://user-images.githubusercontent.com/44652400/201396658-c99115f4-353c-4739-8ad1-e43156c32755.png)

![Need for Sleep™ Under the Cover_2022 11 11-21 29](https://user-images.githubusercontent.com/44652400/201396680-24d460c9-b413-48cb-ba31-5084d7708d85.png)

![Need for Sleep™ Under the Cover_2022 11 11-21 39](https://user-images.githubusercontent.com/44652400/201397950-8e41cdf3-be7b-40b9-b470-98ab1fcf6718.png)

  
</details>

**Comment by xan1242** [comment]
Hm that is supposed to be FONT_APT_AQUARIUS_MEDIUM48 and I'm pretty sure I included that line in the txt file.

Can you check that you have it?

```
FONT_APT_AQUARIUS_MEDIUM48 = 0.3333334 # 28 / 84
```

**Comment by HarGabt** [comment]
I'll check this one later, after I'm back home

**Comment by HarGabt** [comment]
@xan1242
I checked it, and I do have this line, and it works _if I leave an empty line afterwards_. Apparently, my fault of deleting it, thus causing the bug.

**Comment by xan1242** [comment]
Huh? That shouldn't happen...

It's a bug nonetheless. I wrote my own parser for it. Could be because I just used "fgets" to read lines...

**Comment by HarGabt** [comment]
Just for the context:

If i leave it like this - it works
![изображение](https://user-images.githubusercontent.com/44652400/201472536-27ef8c4c-cd15-4c98-b81a-f1f89b55743f.png)

If the condition is this - it doesn't
![изображение](https://user-images.githubusercontent.com/44652400/201472552-05d4ba52-d2ab-4d3c-93d1-4868761fbfe2.png)
