### ISSUE TITLE
FontWiz mentioned in Tools

### ISSUE THREAD

**Issue by muratcansarkalkan** [xan1242/NFS_CustomFont#5]
Hello,

First of all thanks for your contributions. The FFN files you made work stable in other EA games. However in Tools folder's readme, you mentioned about a tool named Fontwiz that saves as .ffn files. I could not find the tool. Is something like that in development, or private?

Best,
Muratcan

**Comment by xan1242** [comment]
It's available in the full package: https://github.com/xan1242/NFS_CustomFont/tree/master/Tools#full-package

Download the package and you'll find the tool there.

**Comment by xan1242** [comment]
Whoops, I see the file is gone, please wait, I have to update the link...

**Comment by xan1242** [comment]
There, the link has been updated, you can download it from there and the tools will be fully available in the package.

**Comment by muratcansarkalkan** [comment]
Thanks for the quick response! I will try it out.
Edit: Works like a charm. If I move to a country that has a PayPal, I'll make a donation.

**Comment by xan1242** [comment]
> Thanks for the quick response! I will try it out.
> 
> Edit: Works like a charm. If I move to a country that has a PayPal, I'll make a donation.

Good to know it worked out for you!

I appreciate the gesture, thank you.
